#!/usr/bin/env python3
"""Build describe.txt and pedia.txt for the standalone ruleset.

`docs/CIVILOPEDIA-TEXT.md` holds the prose; `RULES.txt` holds the entry order the
Civilopedia indexes onto. This script joins the two into the two data files
`CivilopediaLoader` reads, and fails loudly if the document and the ruleset ever
disagree about which entries exist or what order they are in.

Entry text that has not been written yet is emitted as an empty section, which
the loader treats the same as a missing entry.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


REPOSITORY = Path(__file__).resolve().parents[1]
DOCUMENT = REPOSITORY / "docs" / "CIVILOPEDIA-TEXT.md"
STANDALONE = REPOSITORY / "RaylibUI" / "FOSSart" / "Standalone"
RULES = STANDALONE / "RULES.txt"

BANNER = (
    "; Generated by scripts/build_civilopedia_text.py -- do not edit by hand.\n"
    "; Source prose: docs/CIVILOPEDIA-TEXT.md\n"
)

# Facts appended to a unit's description, one per rules flag bit. The order is
# the flag order Unit.Flag(n) reads after RulesParser reverses the bit string.
UNIT_FACTS = [
    "It sees two squares in every direction rather than one.",
    "It ignores enemy zones of control.",
    "It can attack directly from a ship onto a defended shore.",
    "It has the advantages and the restrictions of a submarine.",
    "It can attack enemy air units.",
    "It is lost if it ends a turn away from land.",
    "Its attacks ignore City Walls.",
    "It can carry air units.",
    "It can make paradrops.",
    "It moves as though every square were connected by road.",
    "It defends at double strength against mounted units.",
    "It needs no support under Fundamentalism.",
    "It is destroyed after it attacks.",
    "It defends at double strength against air units.",
]


def rules_sections() -> dict[str, list[str]]:
    """Return the RULES.txt rows of each section this script needs, in file order."""
    lines = RULES.read_text(encoding="utf-8").splitlines()
    sections: dict[str, list[str]] = {}
    current: str | None = None
    for line in lines:
        if line.startswith("@"):
            current = line.strip()
            sections[current] = []
        elif current is not None and line.strip():
            sections[current].append(line)
    return sections


def rules_entries() -> dict[str, list[str]]:
    """Return the entry names of every Civilopedia category, in ruleset order."""
    sections = rules_sections()
    names = lambda rows: [row.split(",")[0].split(";")[0].strip() for row in rows]

    improvements = names(sections["@IMPROVE"])
    wonder_count = len(sections["@ENDWONDER"])
    first_wonder = len(improvements) - wonder_count

    return {
        "advances": names(sections["@CIVILIZE"]),
        "improvements": improvements[:first_wonder],
        "wonders": improvements[first_wonder:],
        "units": names(sections["@UNITS"]),
        "terrain": names(sections["@TERRAIN"]),
        "governments": names(sections["@GOVERNMENTS"]),
    }


DOCUMENT_HEADINGS = {
    "advances": "Advances",
    "units": "Units",
    "improvements": "City Improvements",
    "wonders": "Wonders of the World",
    "terrain": "Terrain",
    "governments": "Governments",
    "concepts": "Concepts",
}


def document_entries() -> dict[str, list[tuple[str, str]]]:
    """Return (name, prose) for every entry of every section of the document."""
    text = DOCUMENT.read_text(encoding="utf-8")
    sections: dict[str, list[tuple[str, str]]] = {}
    for chunk in re.split(r"^## ", text, flags=re.M)[1:]:
        lines = chunk.splitlines()
        title = re.sub(r"\s*\(\d+\)$", "", lines[0]).strip()
        key = next((k for k, v in DOCUMENT_HEADINGS.items() if v == title), None)
        if key is None:
            continue
        entries: list[tuple[str, str]] = []
        for entry in re.split(r"^### ", "\n".join(lines[1:]), flags=re.M)[1:]:
            rows = entry.splitlines()
            name = rows[0].split("*(")[0].strip()
            prose = " ".join(
                row.strip() for row in rows[1:]
                if row.strip() and not row.strip().startswith("<!--")
            )
            entries.append((name, prose))
        sections[key] = entries
    return sections


def reconcile(rules: dict[str, list[str]], doc: dict[str, list[tuple[str, str]]]) -> list[str]:
    """Report every place the document and the ruleset disagree."""
    errors = []
    if not doc.get("concepts"):
        errors.append("the document has no Concepts section")
    for key, names in rules.items():
        if key not in doc:
            errors.append(f"the document has no {DOCUMENT_HEADINGS[key]} section")
            continue
        written = [name for name, _ in doc[key]]
        if written != names:
            only_doc = [n for n in written if n not in names]
            only_rules = [n for n in names if n not in written]
            detail = f"document-only {only_doc}, ruleset-only {only_rules}" \
                if (only_doc or only_rules) else "same entries in a different order"
            errors.append(f"{DOCUMENT_HEADINGS[key]}: {detail}")
    return errors


def index_block(header: str, entries: list[tuple[str, str]]) -> list[str]:
    """Emit an index block plus the description sections it maps onto.

    The loader counts description sections from the line after the index header,
    so writing them immediately after the block's `-2` terminator makes each
    entry's index its own ruleset position.
    """
    lines = [header]
    lines += [f"{position},{name}" for position, (name, _) in enumerate(entries)]
    lines.append("-2")
    for name, prose in entries:
        lines.append(f"@@{name}")
        if prose:
            lines.append(prose)
        lines.append("")
    return lines


def build_describe(rules: dict[str, list[str]], doc: dict[str, list[tuple[str, str]]]) -> str:
    """Build describe.txt: six index blocks, each followed by its descriptions."""
    # The Improvements list the loader indexes covers wonders too, so the wonder
    # slots are padded here and carry their prose in the wonder block instead.
    improvements = doc["improvements"] + [(name, "") for name in rules["wonders"]]

    lines = [BANNER.rstrip("\n")]
    lines += index_block("@@ADVANCE_INDEX", doc["advances"])
    lines += index_block("@@IMPROVEMENT_INDEX", improvements)
    lines += index_block("@@WONDER_INDEX", doc["wonders"])
    lines += index_block("@@UNIT_INDEX", doc["units"])
    lines += index_block("@@TERRAIN_INDEX", doc["terrain"])
    lines += index_block("@@GOVERNMENT_INDEX", doc["governments"])

    # Concepts have no ruleset rows: the loader takes both the menu and the text
    # from this block, so the headings are the names the player sees.
    lines.append("@CONCEPT_DESCRIPTIONS")
    for name, prose in doc["concepts"]:
        lines.append(f"@@{name}")
        if prose:
            lines.append(prose)
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def build_pedia(rules: dict[str, list[str]], doc: dict[str, list[tuple[str, str]]]) -> str:
    """Build pedia.txt: the improvement and wonder panels, and the unit facts."""
    lines = [BANNER.rstrip("\n")]

    # @PEDIAIMPROVE ids run across the whole improvement array, wonders included.
    for position, (name, prose) in enumerate(doc["improvements"] + doc["wonders"]):
        lines.append("@;")
        lines.append(f"@PEDIAIMPROVE{position}")
        if prose:
            lines.append(prose)

    lines.append("@;")
    lines.append("@PEDIAUNITFACTS")
    lines += [f"^{fact}" for fact in UNIT_FACTS]
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="verify the generated files are current without rewriting them")
    args = parser.parse_args()

    rules = rules_entries()
    doc = document_entries()

    errors = reconcile(rules, doc)
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    generated = {
        STANDALONE / "describe.txt": build_describe(rules, doc),
        STANDALONE / "pedia.txt": build_pedia(rules, doc),
    }

    stale = []
    for path, content in generated.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(REPOSITORY).as_posix())
        else:
            path.write_text(content, encoding="utf-8", newline="\n")

    if stale:
        for path in stale:
            print(f"ERROR: {path} is stale; run scripts/build_civilopedia_text.py", file=sys.stderr)
        return 1

    written = sum(1 for entries in doc.values() for _, prose in entries if prose)
    total = sum(len(entries) for entries in doc.values())
    verb = "verified" if args.check else "wrote"
    print(f"Civilopedia text {verb}: {written} of {total} entries carry description text")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
